# Part B.4 - 2 Drones, and 8 obstacles

bounds:
  x: [0, 50]
  y: [0, 50]
  z: [0, 50]

initial_configuration:
  - [1, 1, 1]
  - [3, 1, 1]

obstacles:
  - type: box
    position: [12, 12, 2]
    size: [6, 4, 4]
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [18, 8, 3]
    radius: 2.5
    color: red

  - type: cylinder
    endpoints: [[20, 15, 0], [20, 15, 12]]
    radius: 2.0
    rotation: [0, 0, 0]
    color: red

  - type: box
    position: [30, 18, 2]
    size: [6, 6, 4]
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [22, 24, 4]
    radius: 2.0
    color: red

  - type: box
    position: [35, 10, 2]
    size: [5, 8, 4]
    rotation: [0, 0, 0]
    color: red

  - type: cylinder
    endpoints: [[28, 22, 0], [28, 22, 12]]
    radius: 2.0
    rotation: [0, 0, 0]
    color: red

  - type: box
    position: [15, 30, 2]
    size: [8, 5, 4]
    rotation: [0, 0, 0]
    color: red

goals:
  - position: [20, 20, 5]
    radius: 1.0
  - position: [25, 10, 5]
    radius: 1.0
