# Part B.4 - 2 Drones, and 2 obstacles

bounds:
  x: [0, 50]
  y: [0, 50]
  z: [0, 50]

initial_configuration:
  - [1, 1, 1]
  - [3, 1, 1]

obstacles:
  - type: box
    position: [12, 12, 2]
    size: [6, 4, 4]
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [18, 8, 3]
    radius: 2.5
    color: red

goals:
  - position: [20, 20, 5]
    radius: 1.0
  - position: [25, 10, 5]
    radius: 1.0
