# Part B.4 - 2 Drones, and 0 obstacle

bounds:
  x: [0, 50]
  y: [0, 50]
  z: [0, 50]

initial_configuration:
  - [1, 1, 1]
  - [3, 1, 1]

obstacles: []

goals:
  - position: [20, 20, 5]
    radius: 1.0
  - position: [25, 10, 5]
    radius: 1.0
